code --install-extension benitezdouglas.express-faster
code --install-extension bradlc.vscode-tailwindcss
code --install-extension brenix.hacker-theme
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension dkundel.vscode-new-file
code --install-extension drcika.apc-extension
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension icrawl.discord-vscode
code --install-extension irongeek.vscode-env
code --install-extension jock.svg
code --install-extension ms-azuretools.vscode-docker
code --install-extension naumovs.color-highlight
code --install-extension nmsmith89.incrementor
code --install-extension octref.vetur
code --install-extension pkief.material-icon-theme
code --install-extension planbcoding.vscode-react-refactor
code --install-extension prisma.prisma
code --install-extension ritwickdey.liveserver
code --install-extension sleistner.vscode-fileutils
code --install-extension softwaredotcom.swdc-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension stylelint.vscode-stylelint
code --install-extension supermaven.supermaven
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vscodevim.vim
code --install-extension vue.volar
code --install-extension vunguyentuan.vscode-postcss
code --install-extension wayou.vscode-todo-highlight
code --install-extension yoavbls.pretty-ts-errors